version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql+pymysql://root:qwe123@db:3306/chatbot
    restart: always

  mysql:
    image: mysql
    container_name: mysql-container  # 컨테이너 이름 설정
    restart: always
    ports:
      - "3306:3306"  # 로컬 포트:컨테이너 포트
    environment:
      MYSQL_ROOT_PASSWORD: qwe123  # 루트 유저 비밀번호 설정
      TZ: Asia/Seoul
    platform: linux/x86_64
